package samourai

func Render(_ string) string {
	return `# 🥷 Samouraï Coop

Welcome to the **samourai** namespace — a decentralized playground where creativity meets governance.

## 🌐 What is Samouraï Coop?

SAMOURAÏ COOP is a creative production company born in Paris, France.
It’s mission is to produce films, dapps, music, arts, ads, events and content with a high quality standards, providing it for communities, companies, start-ups, and for its own TV community.
As the world first production company integrating a tech team, with research & development on decentralized protocols, it gives birth to new models to empower artists, users, and humans. 

## 🧰 Featured Realms

Coming soon... (daokit, gnolove, payrolls, ...)

> Dive deeper at [samourai.world](https://www.samourai.world)

`
}
